AptitudeTest.WebApp/ViewModels/AttendExamViewModel.cs
namespace AptitudeTest.WebApp.ViewModels
{
    public class AttendExamViewModel
    {
        public string UserName { get; set; }
        public int CandidateId { get; set; }

        public int ExamId { get; set; }
        public string ExamTitle { get; set; }
        public int NextExamId { get; set; }
        public int ExamTimer { get; set; }

        public List<QnAViewModel> QnAs { get; set; }

        public string Message { get; set; }

    }
}

AptitudeTest.WebApp/ViewModels/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AptitudeTest.WebApp.ViewModels
{
    public class ChangePasswordViewModel
    {
        public string UserName { get; set; }

        [Required]
        public string NewPassword { get; set; }

        [Required]
        [Compare("NewPassword")]
        public string NewPasswordConfirm { get; set; }
    }
}

AptitudeTest.WebApp/Areas/CANDIDATE/Controllers/CandidateController.cs
using AptitudeTest.WebApp.Data;
using AptitudeTest.WebApp.Models;
using AptitudeTest.WebApp.ViewModels;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MimeKit;
using NuGet.Versioning;
using System.Runtime.InteropServices;

namespace AptitudeTest.WebApp.Areas.CANDIDATE.Controllers
{
    [Area("CANDIDATE")]
    public class CandidateController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly EmailConfiguration _emailConfig;

        public CandidateController(ApplicationDbContext context, EmailConfiguration emailConfig)
        {
            _context = context;
            _emailConfig = emailConfig;
        }

        //Chau Anh edit lai Profile
        //Profile
        public IActionResult Profile()
        {
            var userBySession = HttpContext.Session.Get<User>("user");
            var user = _context.Users.FirstOrDefault(u => u.Id == userBySession.Id);
            if (user == null)
            {
                return NotFound();
            }

            var profileViewModel = new CandidateProfileViewModel(user);
            profileViewModel.FinalResultList = _context.FinalResults.Include(fr => fr.Exam).Where(fr => fr.UserId == user.Id).ToList();

            return View(profileViewModel);
        }

        [HttpPost]
        public IActionResult UpdateProfile(CandidateProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userToUpdate = _context.Users.FirstOrDefault(u => u.Id == model.Id);
                if (userToUpdate == null)
                {
                    return NotFound();
                }

                // Update the properties of the retrieved entity with the values from the model
                userToUpdate.UserName = model.UserName;
                userToUpdate.FirstName = model.FirstName;
                userToUpdate.LastName = model.LastName;
                userToUpdate.PhoneNumber = model.PhoneNumber;
                userToUpdate.BirthDay = model.BirthDay;


                // Save changes to the database
                _context.Users.Update(userToUpdate);
                _context.SaveChanges();

                TempData["Success"] = "Successfully Update Candidate";
                return RedirectToAction(nameof(Profile));
            }
            else
            {
                return View("Profile"); // Return to the EditProfile view with validation errors
            }
        }

        //Change Password
        public static string GenerateOTP(int length = 6)
        {
            const string chars = "0123456789";
            var random = new Random();
            var otp = new char[length];

            for (int i = 0; i < length; i++)
            {
                otp[i] = chars[random.Next(chars.Length)];
            }

            return new string(otp);
        }
        private void SendEmail(EmailMessage generateMessage)
        {
            var getMessage = CreateEmailMessage(generateMessage);
            Send(getMessage);
        }
        private MimeMessage CreateEmailMessage(EmailMessage generateMessage)
        {
            var mimeMessage = new MimeMessage();
            mimeMessage.From.Add(new MailboxAddress(" Webster@oilgascompany.com", _emailConfig.From));
            mimeMessage.To.AddRange(generateMessage.To);
            mimeMessage.Subject = generateMessage.Subject;
            mimeMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html) { Text = generateMessage.Content };


            return mimeMessage;
        }
        private void Send(MimeMessage getMessage)
        {
            using var client = new SmtpClient();
            try
            {
                client.Connect(_emailConfig.SmtpServer, _emailConfig.Port, true);
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.Authenticate(_emailConfig.Username, _emailConfig.Password);
                client.Send(getMessage);
            }
            catch
            {
                throw;
            }
            finally
            {
                client.Disconnect(true);
                client.Dispose();
            }
        }

        //Verify OTP to Change Password
        public IActionResult OTPVerify(int id)
        {
            var candidate = _context.Users.FirstOrDefault(u => u.Id == id);
            if (candidate == null)
            {
                return NotFound();
            }

            string otp = GenerateOTP();
            HttpContext.Session.SetString("otp", otp);

            string templateFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "EmailTemplate", "EmailOTP.html"); // Adjust the file path as per your actual location
            string emailContent;

            using (StreamReader reader = new StreamReader(templateFilePath))
            {
                emailContent = reader.ReadToEnd();
            }
            emailContent = emailContent.Replace("{OTP}", otp);
            var generateMessage = new EmailMessage(new string[] { candidate.Email }, "OTP Verification from Webster", emailContent);

            SendEmail(generateMessage);

            return View(candidate);
        }

        [HttpPost]
        public IActionResult OTPVerify(string verifyOtp)
        {
            if (string.IsNullOrEmpty(verifyOtp))
            {
                ModelState.AddModelError("OtpNullError", "Otp Verify must be fill");
                return View();
            }

            var getOTP = HttpContext.Session.GetString("otp");
            if (verifyOtp != getOTP)
            {
                ModelState.AddModelError("OtpWrongError", "Otp verification wrong, please try again");
                return View();
            }

            return RedirectToAction(nameof(ChangePassword));

        }

        //Change Password
        public IActionResult ChangePassword()
        {
            var userBySession = HttpContext.Session.Get<User>("user");
            var user = _context.Users.FirstOrDefault(u => u.Id == userBySession.Id);

            var vm = new ChangePasswordViewModel();
            vm.UserName = user.UserName;

            return View(vm);
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel vm)
        {
            var userBySession = HttpContext.Session.Get<User>("user");
            var user = _context.Users.FirstOrDefault(u => u.Id == userBySession.Id);

            user.Password = vm.NewPasswordConfirm;

            _context.Users.Update(user);
            _context.SaveChanges();

            return RedirectToAction(nameof(Profile));
        }


        //Index Page
        public IActionResult Index()
        {
            var userProfile = HttpContext.Session.Get<User>("user");
            if (userProfile == null)
            {
                return NotFound();
            }

            var exams = _context.Exams.ToList();

            var viewModel = new CandidateIndexViewModel
            {
                UserName = userProfile.UserName,
                Exams = exams,
                ExamCompletionStatus = new List<bool>(),
                CurrentExamIndex = -1
            };

            foreach (var exam in exams)
            {
                var hasTakenExam = _context.ExamResults.Any(er => er.ExamId == exam.Id && er.UserId == userProfile.Id);
                viewModel.ExamCompletionStatus.Add(hasTakenExam);

                if (!hasTakenExam && viewModel.CurrentExamIndex == -1)
                {
                    viewModel.CurrentExamIndex = exams.IndexOf(exam);
                }
            }

            return View(viewModel);
        }


        //Attend Exam
        public IActionResult AttendExam(int examId)
        {
            var model = new AttendExamViewModel();
            var userInfo = HttpContext.Session.Get<User>("user");
            var theLastExamId = _context.Exams.Max(e => e.Id);

            if (userInfo != null)
            {
                model.UserName = userInfo.UserName;
                model.CandidateId = userInfo.Id;
                model.QnAs = new List<QnAViewModel>();
                var getExam = _context.Exams.FirstOrDefault(e => e.Id == examId);
                model.ExamTitle = getExam.Title;
                model.ExamId = examId;
                model.ExamTimer = getExam.Time;

                if (_context.ExamResults.Any(er => er.ExamId == examId && er.UserId == userInfo.Id) == false)
                {
                    var qnaByExamList = _context.QnAs.Where(q => q.ExamId == examId).ToList();
                    var random = new Random();
                    var newRandomQnAList = new List<QnA>();

                    for (var i = 0; i < getExam.TakeRandomCount; i++)
                    {
                        var index = random.Next(0, qnaByExamList.Count);
                        newRandomQnAList.Add(qnaByExamList[index]);
                        qnaByExamList.RemoveAt(index);
                    }

                    model.QnAs = newRandomQnAList.Select(x => new QnAViewModel(x)).ToList();
                    model.Message = "";
                }
                else
                {
                    if (examId == theLastExamId)
                    {
                        model.NextExamId = 0;
                    }
                    else
                    {
                        var exams = _context.Exams.ToList();
                        for (var i = 0; i < exams.Count() - 1; i++)
                        {
                            if (exams[i].Id == examId)
                            {
                                model.NextExamId = exams[i + 1].Id;
                            }
                        }
                    }

                    model.Message = "You are already attend this Exam";
                }

                return View(model);
            }
            else
            {

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/AttendExam.cshtml
@model AttendExamViewModel

@{
    ViewData["Title"] = "AttendExam";
    Layout = "_Layout";
}

<div class="container" style="margin-top: 30px">
    <div class="col">
        <div class="card">
            <div class="card-body">
                @if (Model.Message == "")
                {
                    <div class="container-fluid">

                        <div class="jumbotron">
                            <h3>@Model.ExamTitle</h3>
                        </div>

                        <h1>Time Remaining: <span id="minRemaining"></span>:<span id="secRemaining"></span></h1>

                        <form method="post" asp-controller="Candidate" asp-action="AttendExam">
                            <input type="hidden" asp-for="CandidateId" />
                            <input type="hidden" asp-for="ExamId" />

                            @for (var i = 0; i < Model.QnAs.Count(); i++)
                            {
                                <input type="hidden" asp-for="@Model.QnAs[i].Id" />
                                <input type="hidden" asp-for="@Model.QnAs[i].ExamId" />

                                <div class="card border-info mb-4">
                                    <div class="d-flex justify-content-between align-items-center card-header bg-info text-white" asp-for="@Model.QnAs[i].Question">
                                        <span>@($"Question {i + 1}")</span>
                                    </div>
                                    <div class="collapse show" aria-labelledby="h1">
                                        <div class="card-body">
                                            <p class="font-weight-bold">@Model.QnAs[i].Question</p>
                                            <div class="form-check">
                                                <input style="margin-left: -20px" class="form-check-input test-question" type="radio" asp-for="@Model.QnAs[i].SelectedAnswer" value="1">
                                                <label class="form-check-label">
                                                    @Model.QnAs[i].Option1
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input style="margin-left: -20px" class="form-check-input test-question" type="radio" asp-for="@Model.QnAs[i].SelectedAnswer" value="2">
                                                <label class="form-check-label">
                                                    @Model.QnAs[i].Option2
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input style="margin-left: -20px" class="form-check-input test-question" type="radio" asp-for="@Model.QnAs[i].SelectedAnswer" value="3">
                                                <label class="form-check-label">
                                                    @Model.QnAs[i].Option3
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input style="margin-left: -20px" class="form-check-input test-question" type="radio" asp-for="@Model.QnAs[i].SelectedAnswer" value="4">
                                                <label class="form-check-label">
                                                    @Model.QnAs[i].Option4
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }

                            <button id="submitButton" type="submit" name="action" class="btn btn-primary align-center">Submit Answer</button>
                        </form>
                    </div>
                }
                else
                {
                    <div class="container-fluid">
                        <p style="font-size: 30px; color: red; text-align: center;">@Model.Message</p>
                        @if (Model.NextExamId == 0)
                        {
                            <a asp-area="CANDIDATE" asp-controller="Candidate" asp-action="ExitPage" class="btn btn-success">Your last Exam Has Been Done, Please Exit</a>
                        }
                        else
                        {
                            <a asp-area="CANDIDATE" asp-controller="Candidate" asp-action="AttendExam" asp-route-examId="@Model.NextExamId" class="btn btn-success">Next Exam</a>
                        }
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        var remainSeconds = (@Model.ExamTimer * 60) - 1;
        var secondsCounter = remainSeconds % 60;

        function formatNumber(number) {
            if (number < 10) {
                return '0' + number;
            }
            else {
                return '' + number;
            }
        }

        function startTick() {
            document.getElementById('secRemaining').innerText = formatNumber(secondsCounter);
            document.getElementById('minRemaining').innerText = formatNumber(parseInt(remainSeconds / 60));

            var _tick = setInterval(function () {
                if (remainSeconds > 0) {
                    remainSeconds = remainSeconds - 1;
                    secondsCounter = secondsCounter - 1;
                    document.getElementById('secRemaining').innerText = formatNumber(secondsCounter);
                    document.getElementById('minRemaining').innerText = formatNumber(parseInt(remainSeconds / 60));
                    if (secondsCounter == 0) {
                        secondsCounter = 60;
                    }
                }
                else {
                    alert('Your Exam Time has Expired');
                    clearInterval(_tick);
                }
            }, 1000);
        }

        startTick();

    </script>
}

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/ChangePassword.cshtml
@model AptitudeTest.WebApp.ViewModels.ChangePasswordViewModel

@{
    ViewData["Title"] = "ChangePassword";
}

<h1 style="text-align: center; margin-top: 10px">ChangePassword</h1>

<div class="container">
    <div class="login-box" style="margin: 100px 200px">
        <div class="card">
            <div class="card-body login-card-body">
                <form method="post" asp-action="ChangePassword">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="NewPassword" class="control-label"></label>
                        <input asp-for="NewPassword" class="form-control" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="NewPasswordConfirm" class="control-label"></label>
                        <input asp-for="NewPasswordConfirm" class="form-control" />
                        <span asp-validation-for="NewPasswordConfirm" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input style="border-radius: 30px; margin-left: 40%" type="submit" value="Save Change" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/ExitPage.cshtml
@{
    ViewData["Title"] = "ExitPage";
}

<h1 style="text-align:center;">ExitPage</h1>

<h1 style="text-align:center;">You have done all your exam</h1>

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/Index.cshtml
@model CandidateIndexViewModel
@{
    ViewData["Title"] = "ReadyForExam";
}

<section class="attend-test">
    <div class="container">
        @if (Model.Exams.Count > 0)
        {
            @for (int i = 0; i < Model.Exams.Count; i++)
            {
                <div class="card u-clearfix">
                    <div class="card-body">
                        <h2 class="card-body-heading">@Model.Exams[i].Title</h2>
                        <h3>Time: @Model.Exams[i].Time mins</h3>
                        <ul class="card-body-stars u-clearfix">
                            @Model.Exams[i].Description
                        </ul>
                        @if (Model.ExamCompletionStatus[i])
                        {
                            <a href="#" class="card-button card-button-cta disabled">Exam Has Been Taken</a>
                        }
                        else if (i == Model.CurrentExamIndex)
                        {
                            <a href="@Url.Action("AttendExam", "Candidate", new { examId = Model.Exams[i].Id })" class="card-button card-button-cta active">
                                Take exam
                            </a>
                        }
                        else
                        {
                            <a href="#" class="card-button card-button-cta disabled">Exam Not Available</a>
                        }
                    </div>
                </div>
            }
        }
        <div id="notificationBox" class="info_box">
            <div class="info-title"><span>Begin the Test</span></div>
            <div class="info-list">
                <div class="info">1. After clicking  <span style="font-weight: 500; color: var(--primary-color-200);">'Start'</span> , the test timer will begin counting down.</div>
                <div class="info">2. You can't select any option once time goes off.</div>
                <div class="info">3. You'll get points on the basis of your correct answers.</div>
            </div>
            <div class="buttons">
                <button id="startTestButton" class="btn btn-primary" onclick="startTest()">Start</button>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        // Function to show the notification box
        function showTestNotification() {
            var notificationBox = document.getElementById('notificationBox');
            notificationBox.style.display = 'block';
        }

        window.onload = function () {
            var takeExamButtons = document.querySelectorAll('.card-button-cta.active');
            for (var i = 0; i < takeExamButtons.length; i++) {
                takeExamButtons[i].addEventListener('click', showTestNotification);
            }
        };
    </script>

}

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/OTPVerify.cshtml
@model AptitudeTest.WebApp.Models.User

@{
    ViewData["Title"] = "OTPVerify";
}

<h1 style="text-align:center; margin-top: 10px">Verify to Change Password</h1>


<div class="container">
    <div class="login-box" style="margin: 100px 200px">
        <div class="card">
            <div class="card-body login-card-body">
                <form asp-action="OTPVerify">
                    <input type="text" name="verifyOtp" class="form-control" />
                    <span class="text-danger">@Html.ValidationMessage("OtpNullError")</span>
                    <span class="text-danger">@Html.ValidationMessage("OtpWrongError")</span>

                    <input style="border-radius: 30px; margin-left: 40%" type="submit" value="Submit" class="btn btn-primary" />
                </form>
                <div>
                    <a asp-action="Profile">Back to Profile</a>
                </div>
            </div>
        </div>

       
        </div>
        </div>

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/Profile.cshtml
@model CandidateProfileViewModel
@{
    Layout = "_Layout";
}

<div class="container" style="margin-top: 30px">
    <div class="col">
        <div class="card">
            <div class="card-body">
                @if (!string.IsNullOrEmpty(Model.ProfilePicture))
                {
                    <img style="border-radius: 50%; width: 200px; height: 200px; margin: 0 430px 0 430px" src="~/profileimg/@Model.ProfilePicture" alt="Profile Picture" />
                }
                <form method="post" asp-area="CANDIDATE" asp-controller="Candidate" asp-action="UpdateProfile">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="Email" />
                    <input type="hidden" asp-for="Password" />

                    <div class="row mb-3">
                        <div class="col-sm-4">
                            <h3 class="mb-0">User Name</h3>
                        </div>
                        <div class="col-sm-12 text-secondary">
                            <input class="form-control" asp-for="UserName">
                        </div>
                        <span class="text-danger">@Html.ValidationMessageFor(model => model.UserName)</span>
                    </div>

                    <div class="row gx-3 mb-3">
                        <!-- Form Group (first name)-->
                        <div class="col-md-6">
                            <h3 class="mb-0">First Name</h3>
                            <input class="form-control" asp-for="FirstName">
                        </div>
                        <!-- Form Group (last name)-->
                        <div class="col-md-6">
                            <h3 class="mb-0">Last Name</h3>
                            <input class="form-control" asp-for="LastName">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-sm-4">
                            <h3 class="mb-0">Phone</h3>
                        </div>
                        <div class="col-sm-12 text-secondary">
                            <input class="form-control" asp-for="PhoneNumber">
                        </div>
                        <span class="text-danger">@Html.ValidationMessageFor(model => model.PhoneNumber)</span>
                    </div>

                    <div class="row mb-3">
                        <div class="col-sm-4">
                            <h3 class="mb-0">Date of Birth</h3>
                        </div>
                        <div class="col-sm-12 text-secondary">
                            <input class="form-control" asp-for="BirthDay">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3"></div>

                        <div class="col-sm-9 text-secondary" style="margin-left: 40%">
                            <input type="submit" value="CHANGE YOUR PROFILE" class="btn btn-primary" />
                        </div>


                        <div class="col-sm-9 text-secondary" style="margin-left: 40%">
                            <a asp-action="OTPVerify" asp-route-id="@Model.Id">Change Password</a>
                        </div>

                        <div class="col-sm-9 text-secondary" style="margin-left: 40%">
                            <a asp-action="Index">Back to Home</a>
                        </div>
                    </div>
                </form>

                <div class="row">
                    <h2>Your Exam Result</h2>
                </div>

                @if (Model.FinalResultList.Count() == 0)
                {
                    <div>
                        <h2>Please Take Exam to Record Your Result</h2>
                    </div>
                }
                else
                {
                    <div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Exam Name</th>
                                    <th>Mark</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.FinalResultList)
                                {
                                    <tr>
                                        <td>@item.Exam.Title</td>
                                        @if (item.CountCorrect >= 3)
                                        {
                                            <td style="color:forestgreen">@item.CountCorrect</td>
                                        }
                                        else
                                        {
                                            <td style="color:red">@item.CountCorrect</td>
                                        }
                                        @if (item.Status == true)
                                        {
                                            <td style="color:forestgreen">PASS</td>
                                        }
                                        else
                                        {
                                            <td style="color:red">FAIL</td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // JavaScript to handle password confirmation
        const newPasswordInput = document.getElementById("Password");
        const confirmPasswordInput = document.getElementById("confirmPassword");

        confirmPasswordInput.addEventListener("input", function () {
            if (newPasswordInput.value !== confirmPasswordInput.value) {
                confirmPasswordInput.setCustomValidity("Passwords do not match.");
            } else {
                confirmPasswordInput.setCustomValidity("");
            }
        });
    </script>
}

AptitudeTest.WebApp/Areas/CANDIDATE/Views/Candidate/ShowResult.cshtml
@model FinalResultViewModel

<h1>Candidate info: <strong>@Model.UserInfo.UserName</strong></h1>

<h1>Final Result of <strong>@Model.ExamInfo.Title</strong> Exam</h1>

<h2>Result: <strong>@Model.FinalResult.CountCorrect</strong> / 5</h2>
<h2>Status: <strong>@Model.FinalResult.Status</strong></h2>

@if(Model.ExamInfo.Id <= 3)
{
    <a asp-area="CANDIDATE" asp-controller="Candidate" asp-action="AttendExam" asp-route-examId="@Model.NextExamId">Next Exam</a>
}
else
{
    <h2>You have done all your Exam, please wait for result!!!</h2>
}